version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    restart: always
    container_name: reynir_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_USER=reynir
      - POSTGRES_PASSWORD=reynir
  greynir:
    build: ./
    container_name: greynir
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LANG=is_IS.UTF-8
      - GREYNIR_DB_HOST=db
      - LANGUAGE=is_IS:is
      - FLASK_ENV=development
      - REYNIR_DIR=/reynir/src/Greynir
    volumes:
      - ./conf/bin:/reynir/bin
      - ./logs:/reynir/logs
      - ./conf/cron/tasks.cron:/var/spool/cron/crontabs/root
    command: /reynir/bin/start.sh
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    container_name: reynir_nginx
    ports:
      - "5050:5050"
    volumes:
      - ./conf/nginx/greynir:/etc/nginx/nginx.conf
    depends_on:
      - greynir
volumes:
  dbdata:
