version: '3'
services:
  greynir:
    build: ./
    container_name: greynir
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/reynir/logs
      - ./conf/cron/tasks.cron:/var/spool/cron/crontabs/root
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "5050:5050"
    volumes:
      - ./conf/nginx/greynir:/etc/nginx/nginx.conf
    depends_on:
      - greynir
