version: '3'
services:
  greynir:
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - ./src:/reynir/src
      - ./conf/bin:/reynir/bin
    command: /reynir/bin/start_dev.sh
  nnserver:
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
