version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile-postgres
    restart: always
    container_name: reynir_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"   
    environment:
      - POSTGRES_USER=reynir
      - POSTGRES_PASSWORD=reynir
  greynir:
    build: ./
    container_name: greynir
    restart: always
    ports:
      - "5050:5000"
    environment:
      - LANG=is_IS.UTF-8
      - GREYNIR_DB_HOST=db
      - LANGUAGE=is_IS:is
      - FLASK_ENV=development
    volumes:
      - ./start.sh:/start.sh
    command: /start.sh
    depends_on:
      - db
volumes:
  dbdata:
