version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    restart: always
    container_name: reynir_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  dbdata:
